name: Github Enterprise Configuration
on: workflow_dispatch


env:
    ENTERPRIZE: Delaware Consulting CVBA
    ORGANIZATION: DLW-INT-CMC
    REPOSITORY: TESTGA
    OWNER_NAME: Emre-Igten
    USER_NAME: Emre-Igten
    BRANCH: main


jobs:
  check-info:
    runs-on: ubuntu-latest

    steps:
        - name: Check if user is collaborator in repo
          run: |
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ env.OWNER_NAME }}/${{ env.REPOSITORY }}/collaborators/${{ env.USER_NAME }}


    
        - name: Get Branch Protections
          run: |
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER_NAME }}/${{ env.REPOSITORY }}/branches/${{ env.BRANCH }}/protection